### ISSUE TITLE
New CI test matrix with GH Actions

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#5077]
Since I'm porting our MacOS + Linux CI from Travis to Github Actions, it is a good time to reconsider whether we're happy with our matrix of test cases. 

Here is the current Travis matrix
```yaml
matrix:
  include:
    - os: linux
      python: 3.6
      stage: Comprehensive tests
      env: OPTIONAL_DEPS=1 WITH_PYSIDE=1 BUILD_DOCS=1 INSTALL_FROM_SDIST=1
    - os: linux
      python: 3.6
      stage: Comprehensive tests
      env: QT=PyQt5 MINIMUM_REQUIREMENTS=1
    - os: linux
      python: 3.6
      stage: Comprehensive tests
      env: PYTHONOPTIMIZE=2 BUILD_DOCS=0 TEST_EXAMPLES=0
    - os: linux
      python: 3.6
      stage: Comprehensive tests
      env: QT=PyQt5 OPTIONAL_DEPS=1 MINIMUM_REQUIREMENTS=1
    - os: linux
      python: 3.7
      stage: Comprehensive tests
      dist: xenial # Required for Python 3.7+
      env: QT=PyQt5 OPTIONAL_DEPS=1 BUILD_DOCS=1 DEPLOY_DOCS=1
      services:
        - xvfb
    - os: linux
      python: 3.7
      stage: Comprehensive tests
      # Testing and installing from sdist will ensure that tests do not
      # depend on pooch to pass
      # pooch is used as an optional dependency to download datasets on the fly
      # users installing scikit-image in development mode do not require
      # pooch to run the tests
      env: INSTALL_FROM_SDIST=1
      dist: xenial # Required for Python 3.7
      services:
        - xvfb
    - os: linux
      python: 3.7
      stage: Comprehensive tests
      dist: xenial # Required for Python 3.7
      env: QT=PyQt5 OPTIONAL_DEPS=1 BUILD_DOCS=1
      services:
        - xvfb
    - os: linux
      python: 3.8
      stage: Initial tests
      env: QT=PyQt5 OPTIONAL_DEPS=1 BUILD_DOCS=1
      dist: xenial # Required for Python 3.7+
      services:
        - xvfb
    - os: linux
      python: 3.7
      stage: Comprehensive tests
      env: QT=PyQt5 OPTIONAL_DEPS=1 PIP_FLAGS="--pre"
      dist: xenial # Required for Python 3.7
      services:
        - xvfb
    # For smooth deployment, the osx_image here should match
    # what we set in the wheel generation travis images.
    # If not set, it will use the default version from Travis
    # https://docs.travis-ci.com/user/reference/osx/#xcode-version
    - os: osx
      osx_image: xcode9.4
      language: objective-c
      stage: Comprehensive tests
      env: MB_PYTHON_VERSION=3.6 TEST_EXAMPLES=0
    - os: osx
      osx_image: xcode9.4
      language: objective-c
      stage: Comprehensive tests
      env: MB_PYTHON_VERSION=3.7 OPTIONAL_DEPS=1 EXTRA_DEPS=0
    - os: osx
      osx_image: xcode9.4
      language: objective-c
      stage: Initial tests
      env: MB_PYTHON_VERSION=3.8 OPTIONAL_DEPS=1 EXTRA_DEPS=0

```

`DEPLOY_DOCS` was not used any more, but apart from that, is there anything which I should change? For example, should the `pre` build run with py3.8 instead of 3.7? (There will be py3.9 to add as well, but let's first try to reproduce what we had with Travis). Should the build testing minimum requirements be on py3.7 instead of 3.6?
