### ISSUE TITLE
 Verify wheel artifact attestation broken

### ISSUE THREAD

**Issue by jarrodmillman** [scikit-image/scikit-image#7443]
### Description:

Release 0.24.0rc0 isn't on PyPI because the GH action failed:
https://github.com/scikit-image/scikit-image/actions/runs/9528066073/job/26266131975
with this error:
```
Run gh attestation verify dist/scikit_image-*.whl --repo scikit-image/scikit-image
  gh attestation verify dist/scikit_image-*.whl --repo scikit-image/scikit-image
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.12.3/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.3/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.3/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.3/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.3/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.3/x64/lib
    GH_TOKEN: ***
too many arguments
```

I believe `gh attestation verify` is meant to verify a single artifact and it works fine when you try to verify a single artifact. For example, it works for the sdist artifact (we use a file glob, but there is only one sdist file):
```
Run gh attestation verify dist/scikit_image-*.tar.gz --repo scikit-image/scikit-image
  gh attestation verify dist/scikit_image-*.tar.gz --repo scikit-image/scikit-image
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.12.3/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.3/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.3/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.3/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.3/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.3/x64/lib
    GH_TOKEN: ***
scikit-image/scikit-image	https://slsa.dev/provenance/v1	.github/workflows/wheel_tests_and_release.yml@refs/tags/v0.24.0rc0
```

Here are the artifacts:
https://github.com/scikit-image/scikit-image/attestations
