### ISSUE TITLE
Missing scikit-image nightly wheels on MacOS

### ISSUE THREAD

**Issue by phofl** [scikit-image/scikit-image#7607]
We installed the nightlies in Dask CI (usually from here: https://pypi.anaconda.org/scientific-python-nightly-wheels/simple), but we are getting errors that the wheels can't be found there anymore (and seem to be gone), is this intended and if yes is there another source?

**Comment by jarrodmillman** [comment]
The nightly wheels action has been failing:
https://github.com/scikit-image/scikit-image/actions/workflows/nightly_wheel_build.yml

The error is
```
MACOSX_DEPLOYMENT_TARGET=10.9
MACOS_DEPLOYMENT_TARGET=10.9
sudo: conda: command not found
```
or
```
MACOSX_DEPLOYMENT_TARGET=12.0
MACOS_DEPLOYMENT_TARGET=12.0
sudo: conda: command not found
Error: Process completed with exit code 1.
```

We should probably be using more recent versions anyway.

**Comment by jarrodmillman** [comment]
Might be time to get PR #7407 merged.

**Comment by stefanv** [comment]
Thank you for reporting, @phofl. We've identified an issue with our nightly wheel builder pipeline, and will address that ASAP.

**Comment by lagru** [comment]
Hmm, https://github.com/scikit-image/scikit-image/pull/7407 seems somewhat unrelated. That was an attempt to fix the macos tests that don't use conda to setup libomp. The failure for the nightly wheels seems to use conda to setup the "oldest supported [libomp] version" that will be vendored in the wheels. 🤔

**Comment by lagru** [comment]
It seems that [GitHub no longer includes conda in the macos-13 image](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md) as the error message also implies. So we either find a way to include the correct libomp version without conda or find a way to setup conda again.

**Comment by lagru** [comment]
We could copy a [snippet from SciPy to setup conda](https://github.com/scipy/scipy/blob/ae5f5bb927acf99f19e2b64987672035cd2f1913/.github/workflows/macos.yml#L77-L87)

```yml
    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@a4260408e20b96e80095f42ff7f1a15b27dd94ca # v3.0.4
      with:
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        channel-priority: true
        activate-environment: scipy-dev
        use-only-tar-bz2: false
        miniforge-variant: Miniforge3
        miniforge-version: latest
        use-mamba: true
```
I'm not at all familiar with homebrew so I'm not sure how we would install llvm-openmp-11.1.0 via `brew`.
